# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5dba7ab6e03e9d9d2a3479d2d1dabe01ca033789559c513cd7599ef6f5847f1238878ebe5f7d760caf5f900f69ea8234560ca77be7ed468a5a35f3c8b052d57a

test:
  secret_key_base: f1628a3be268941b6f709f1039991108b603672deaf1a68b4823d254cf485643341a468422dc17b3295f2bd73d0c01a481a2ba8e8021a0003321ffdf365aa6ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
